# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import eos_test.eos_crypto.bigint
import eos_test.eos_crypto.elgamal
import eos_test.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElGamalPrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', eos_test.fields.ObjectField(field_type=eos_test.eos_crypto.elgamal.ElGamalPublicKey)),
                ('a', eos_test.fields.ObjectField(field_type=eos_test.eos_crypto.bigint.BigInt)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', eos_test.fields.ObjectField(field_type=eos_test.eos_crypto.bigint.BigInt)),
            ],
        ),
    ]
