# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import eos_core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tasks', eos_core.fields.EosListField(element_type=None)),
            ],
        ),
    ]
