# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import eos_core.fields
import eos_core.libobjects.python
import eos_core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter', eos_core.fields.EosObjectField(field_type=None)),
                ('encrypted_vote', eos_core.fields.EosObjectField(field_type=None)),
                ('vote_received_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, eos_core.libobjects.python.EosDictObject),
            metaclass=eos_core.models.EosDictObjectModelType,
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('election_name', models.CharField(max_length=100)),
                ('questions', eos_core.fields.EosListField(element_type=None)),
                ('voter_eligibility', eos_core.fields.EosObjectField(field_type=None)),
                ('voting_opens_at', models.DateTimeField(null=True)),
                ('voting_closes_at', models.DateTimeField(null=True)),
                ('frozen_at', models.DateTimeField(null=True)),
                ('voting_extended_until', models.DateTimeField(null=True)),
                ('voting_opened_at', models.DateTimeField(null=True)),
                ('voting_closed_at', models.DateTimeField(null=True)),
                ('result', eos_core.fields.EosListField(element_type=None, null=True)),
                ('result_released_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, eos_core.libobjects.python.EosDictObject),
            metaclass=eos_core.models.EosDictObjectModelType,
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(max_length=100)),
                ('tasks', eos_core.fields.EosListField(element_type=None)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, eos_core.libobjects.python.EosDictObject),
            metaclass=eos_core.models.EosDictObjectModelType,
        ),
        migrations.AddField(
            model_name='election',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eos_core.Workflow'),
        ),
        migrations.AddField(
            model_name='castvote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eos_core.Election'),
        ),
    ]
