# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import eos_core.fields
import eos_core.libobjects.python
import eos_core.models
import eos_sgjjr.crypto
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eos_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionWithTrustees',
            fields=[
                ('election_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eos_core.Election')),
            ],
            options={
                'verbose_name_plural': 'elections with trustees',
            },
            bases=('eos_core.election',),
            metaclass=eos_core.models.EosDictObjectModelType,
        ),
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(models.Model, eos_core.libobjects.python.EosDictObject),
            metaclass=eos_core.models.EosDictObjectModelType,
        ),
        migrations.CreateModel(
            name='SGJJRTrustee',
            fields=[
                ('trustee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eos_sgjjr.Trustee')),
                ('auth_user_id', models.IntegerField()),
                ('public_key', eos_core.fields.EosObjectField(editable=False, null=True, py_type=eos_sgjjr.crypto.TDH1PublicKey)),
            ],
            options={
                'abstract': False,
            },
            bases=('eos_sgjjr.trustee',),
            metaclass=eos_core.models.EosDictObjectModelType,
        ),
        migrations.AddField(
            model_name='trustee',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eos_sgjjr.ElectionWithTrustees'),
        ),
    ]
